### PR TITLE
SpeechSDK 1.22.0

### PR DESCRIPTION
**Pull request by mzachar**
SDK binaries for 1.21.0

Linked with https://github.com/jabber-tools/cognitive-services-speech-sdk-rs/pull/3

### CODE REVIEW

**Comment by adambezecny** [comment]
hi,

the version currently available under link https://aka.ms/csspeech/linuxbinary  is 1.22. Would it be actually possible to base this PR on this version? Also I would like to include binaries for Mac (https://aka.ms/csspeech/macosbinary). Once done I can approve and merge this PR quickly. Then we can proceed with https://github.com/jabber-tools/cognitive-services-speech-sdk-rs/pull/3

**Comment by mzachar** [comment]
How do you propose I should include the mac library as it has ~208MB compressed.

Github would not allow you to push such commit.

One way is to enable LFS but then the clients that are checking the repository out needs to have support for it too.
Is LFS already enabled on this repository?

**Comment by mzachar** [comment]
I check and it looks like the binary files are stored directly in the git repository (not as LFS)

I cloud migrate them with [git-lfs-migrate](https://github.com/git-lfs/git-lfs/blob/v2.2.0/docs/man/git-lfs-migrate.1.ronn) but that would rewrite the history.

**Comment by adambezecny** [comment]
ok, it really seems mac version of lib has grown significantly since 1.16. we are not supporting build for mac anyway so screw that. we should be fine with linux only. Anyway before I merge let me ask again: what would it involve to go to 1.22 directly?

**Comment by mzachar** [comment]
I'm evaluating the API changes if I do not hit a roadblock I count on updating this pull request to include 1.22.0

**Review by adambezecny — APPROVED** [review]

**Pull request merged**
